# Run playbook with the commands:
#  export AZURE_SUBSCRIPTION_ID="<INSERT SUBSCRIPTION ID HERE>"
#  ansible-playbook complete-kafka-vm.yml
- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: kafkaansible.kamaso.dev
      location: northeurope
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: kafkaansible.kamaso.dev
      name: myVnet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: kafkaansible.kamaso.dev
      name: mySubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: myVnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: kafkaansible.kamaso.dev
      allocation_method: Static
      name: myPublicIP
    register: output_ip_address
  - name: Dump public IP for VM which will be created
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: kafkaansible.kamaso.dev
      name: myNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          source_address_prefix: "Corporate_Public_ip/32"
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: kafkaansible.kamaso.dev
      name: myNIC
      virtual_network: myVnet
      subnet: mySubnet
      security_group: myNetworkSecurityGroup
      ip_configurations:
        - name: ipconfig1
          public_ip_address_name: myPublicIP
          primary: True
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: kafkaansible.kamaso.dev
      name: myVM
      vm_size: Standard_DS1_v2
      admin_username: centos
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/centos/.ssh/authorized_keys
          key_data: <KEY>
      network_interfaces: myNIC
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
      managed_disk_type: Standard_LRS
      data_disks:
        - lun: 0
          disk_size_gb: 100
          managed_disk_type: Standard_LRS
        - lun: 1
          disk_size_gb: 200
          managed_disk_type: Premium_LRS
#- name: remove vm and all resources except public ips
#  azure_rm_virtualmachine:
#    resource_group: kafkaansible.kamaso.dev
#    name: MyVM
#    state: absent
#    remove_on_absent:
#        - network_interfaces
#        - virtual_storage

# See for example of automation:
# https://docs.microsoft.com/en-us/azure/virtual-machines/linux/tutorial-automate-vm-deployment
