- hosts: master_nodes
  roles:
    - { role: elasticsearch, es_instance_name: "masternode", es_heap_size: "1g",
    es_config: {
        cluster.name: "test-cluster", 
        discovery.zen.ping.unicast.hosts: "node4:9300",
        http.port: 9200,
        transport.tcp.port: 9300,
        node.data: false,
        node.master: true,
        bootstrap.mlockall: false,
        discovery.zen.ping.multicast.enabled: false }
    }
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    ansible_user: ansible
    es_plugins:
     - plugin: elasticsearch/license
       version: latest

- hosts: data_nodes
  roles:
    - { role: elasticsearch, es_instance_name: "datanode1", es_data_dirs: "/opt/elasticsearch", 
    es_config: {
        discovery.zen.ping.unicast.hosts: "node4:9300",
        http.port: 9200,
        transport.tcp.port: 9300,
        node.data: true,
        node.master: false,
        bootstrap.mlockall: false,
        cluster.name: "test-cluster",
        discovery.zen.ping.multicast.enabled: false } 
    }
    - { role: elasticsearch, es_instance_name: "datanode2", 
    es_config: {
        discovery.zen.ping.unicast.hosts: "node4:9300",
        http.port: 9201,
        transport.tcp.port: 9301,
        node.data: true,
        node.master: false,
        bootstrap.mlockall: false,
        cluster.name: "test-cluster",
        discovery.zen.ping.multicast.enabled: false } 
    }
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_plugins:
     - plugin: elasticsearch/license
       version: latest
     - plugin: marvel-agent
     - plugin: lmenezes/elasticsearch-kopf
